# Generated by Django 4.2.1 on 2023-05-22 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mentorias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_arquivo', models.CharField(max_length=50, verbose_name='Nome do arquivo')),
                ('arquivo', models.FileField(upload_to=mentorias.models.user_directory_path, validators=[mentorias.models.file_size], verbose_name='Arquvio')),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data criação:')),
                ('controle', models.TextField(blank=True, help_text='Anotações do Programa para seu controle. Apenas você terá acesso a este conteúdo.', null=True, verbose_name='Anotações do Programa')),
                ('etapas', models.JSONField(blank=True, null=True, verbose_name='Etapas do Programa')),
                ('arquivos_programa', models.ManyToManyField(blank=True, help_text='Arquivos de um Programa são arquivos disponíveis aos estudantes                 que fizerem parte do Programa.', null=True, to='mentorias.arquivosprograma')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
