# Generated by Django 3.2.18 on 2023-07-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacaosimulado',
            name='simulado_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo do simulado'),
        ),
        migrations.AlterField(
            model_name='simulados',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título do simulado'),
        ),
    ]
