# Generated by Django 4.2.1 on 2023-05-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0002_arquivosaluno_gabaritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas',
            name='titulo',
            field=models.CharField(help_text='Insira um título para o programa.', max_length=100, verbose_name='Titulo do programa'),
        ),
    ]
