# Generated by Django 4.0 on 2023-08-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0003_alter_alunos_arquivos_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosmentoria',
            name='simulado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorias.simulados'),
        ),
        migrations.AddField(
            model_name='simulados',
            name='pdf_prova',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.arquivosmentoria'),
        ),
    ]
