# Generated by Django 4.2.1 on 2023-05-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0003_alter_programas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas',
            name='arquivos_programa',
            field=models.ManyToManyField(blank=True, help_text='Arquivos de um Programa são arquivos disponíveis aos estudantes                 que fizerem parte do Programa.', to='mentorias.arquivosprograma'),
        ),
    ]
