# Generated by Django 4.0 on 2023-08-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0005_alter_simulados_pdf_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulados',
            name='arquivo_prova',
        ),
    ]
