# Generated by Django 4.0 on 2023-08-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0006_remove_simulados_arquivo_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivosmentoria',
            name='simulado',
        ),
    ]
