# Generated by Django 4.0 on 2023-08-04 23:59

from django.db import migrations, models
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0007_remove_arquivosmentoria_simulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='senha_do_aluno',
            field=models.CharField(blank=True, default=mentorias.models.get_random_string, max_length=8, null=True, verbose_name='Senha para acesso'),
        ),
    ]
