# Generated by Django 4.0 on 2023-08-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0008_alter_matriculaalunomentoria_senha_do_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulados',
            name='estatisticas',
            field=models.JSONField(blank=True, null=True, verbose_name='Estatísticas'),
        ),
    ]
