# Generated by Django 4.0 on 2023-08-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0010_alter_simulados_questao_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacaosimulado',
            options={'ordering': ['-criada_em', 'aluno']},
        ),
    ]
