# Generated by Django 4.0 on 2023-08-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0011_alter_aplicacaosimulado_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulados',
            name='pontuacao',
        ),
        migrations.RemoveField(
            model_name='simulados',
            name='questao_qtd',
        ),
        migrations.AddField(
            model_name='mentoria',
            name='estatisticas',
            field=models.JSONField(blank=True, null=True, verbose_name='Estatísticas'),
        ),
    ]
