# Generated by Django 4.0 on 2023-08-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0013_remove_mentoria_matriculas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='mentoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_mentoria', to='mentorias.mentoria'),
        ),
    ]
