# Generated by Django 4.0 on 2023-08-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0014_alter_matriculaalunomentoria_mentoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='simulados',
            field=models.ManyToManyField(blank=True, to='mentorias.Simulados'),
        ),
    ]
