# Generated by Django 4.0 on 2023-08-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0015_materias_simulados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='arquivos_aluno',
        ),
        migrations.AddField(
            model_name='arquivosmentoria',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_aluno', to='mentorias.alunos'),
        ),
        migrations.DeleteModel(
            name='ArquivosDoAluno',
        ),
    ]
