# Generated by Django 4.2.1 on 2023-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0016_rename_created_mentorias_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostassimulados',
            name='aluno_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Aluno'),
        ),
    ]
