# Generated by Django 4.0 on 2023-08-11 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0016_remove_alunos_arquivos_aluno_arquivosmentoria_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosmentoria',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_matricula', to='mentorias.matriculaalunomentoria'),
        ),
        migrations.AlterField(
            model_name='simulados',
            name='pdf_prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_prova', to='mentorias.arquivosmentoria'),
        ),
    ]
