# Generated by Django 4.0 on 2023-08-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0017_arquivosmentoria_matricula_alter_simulados_pdf_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosmentoria',
            name='mentoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentoria_arquivos', to='mentorias.mentoria'),
        ),
    ]
