# Generated by Django 4.2.1 on 2023-05-26 23:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorias', '0018_rename_aluno_email_respostassimulados_email_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivosaluno',
            old_name='aluno',
            new_name='student_user',
        ),
        migrations.RenameField(
            model_name='arquivosmentoria',
            old_name='arquivo_mentor',
            new_name='arquivo_mentoria',
        ),
        migrations.RemoveField(
            model_name='arquivosaluno',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='arquivosaluno',
            name='aluno_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aluno:'),
        ),
        migrations.AddField(
            model_name='arquivosaluno',
            name='arquivo_aluno',
            field=models.FileField(help_text='Insira arquivo em .pdf de até 5MB de tamanho.', null=True, upload_to=mentorias.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), mentorias.models.file_size], verbose_name='Arquvio mentoria'),
        ),
        migrations.AddField(
            model_name='arquivosaluno',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arquivosaluno',
            name='mentor_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Criado por:'),
        ),
    ]
