# Generated by Django 4.0 on 2023-08-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0018_alter_arquivosmentoria_mentoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoria',
            name='arquivos_da_mentoria',
        ),
    ]
