# Generated by Django 4.2.1 on 2023-05-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0020_arquivosaluno_email_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostassimulados',
            name='simulado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulado_respondido', to='mentorias.simulados'),
        ),
    ]
