# Generated by Django 4.0 on 2023-08-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0020_alter_mentoria_resumo_mentoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacaosimulado',
            name='resposta_alunos',
        ),
        migrations.AddField(
            model_name='aplicacaosimulado',
            name='resposta_aluno',
            field=models.JSONField(blank=True, null=True, verbose_name='Resposta do Aluno'),
        ),
    ]
