# Generated by Django 4.0 on 2023-08-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0021_remove_aplicacaosimulado_resposta_alunos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicacaosimulado',
            old_name='resposta_aluno',
            new_name='resposta_alunos',
        ),
    ]
