# Generated by Django 4.0 on 2023-08-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0022_rename_resposta_aluno_aplicacaosimulado_resposta_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosmentoria',
            name='titulo_arquivo',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome do arquivo'),
        ),
    ]
