# Generated by Django 4.2.1 on 2023-05-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0022_remove_arquivosaluno_mentor_arquivosaluno_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivosaluno',
            name='aluno_nome',
        ),
    ]
