# Generated by Django 4.2.1 on 2023-05-27 01:21

import django.core.validators
from django.db import migrations, models
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0023_remove_arquivosaluno_aluno_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='turma_matriculada',
        ),
        migrations.AlterField(
            model_name='arquivosaluno',
            name='arquivo_aluno',
            field=models.FileField(help_text='Insira arquivo em .pdf de até 5MB de tamanho.', null=True, upload_to=mentorias.models.aluno_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), mentorias.models.file_size], verbose_name='Arquvio mentoria'),
        ),
        migrations.DeleteModel(
            name='Turmas',
        ),
    ]
