# Generated by Django 4.2.1 on 2023-05-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0024_remove_alunos_turma_matriculada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='situacao_matricula',
            field=models.CharField(choices=[('ok', 'Aluno ativo.'), ('ex', 'Ex-aluno.')], default='ok', help_text='Se é aluno atual, ou ex-aluno.', max_length=2, verbose_name='Situação'),
        ),
    ]
