# Generated by Django 4.0 on 2023-08-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0025_materias_em_uso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RespostasSimulados',
        ),
    ]
