# Generated by Django 4.0 on 2023-08-28 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0027_remove_descontos_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaalunomentoria',
            name='encerrada',
            field=models.BooleanField(default=False, verbose_name='Encerrada ou ativa'),
        ),
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da matrícula'),
        ),
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='encerra_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Encerramento mentoria'),
        ),
        migrations.CreateModel(
            name='RegistrosMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do registro')),
                ('log_mentor_id', models.IntegerField(null=True, verbose_name='Id do mentor')),
                ('log_mentor_nome', models.TextField(null=True, verbose_name='Nome do mentor')),
                ('log_mentor_email', models.EmailField(max_length=254, null=True, verbose_name='Email do mentor')),
                ('log_matricula_id', models.IntegerField(null=True, verbose_name='Id da matrícula')),
                ('log_matricula_email', models.EmailField(max_length=254, null=True, verbose_name='Email do aluno nesta matrícula')),
                ('log_matricula_encerra_em', models.DateTimeField(null=True, verbose_name='Data encerramento da matrícula')),
                ('log_mentoria_id', models.IntegerField(null=True, verbose_name='Id da mentoria')),
                ('log_mentoria_titulo', models.TextField(null=True, verbose_name='Título da mentoria')),
                ('atividade', models.CharField(choices=[('cria', 'Matrícula foi criada'), ('ence', 'Matrícula foi encerrada'), ('alte', 'Matrícula foi alterada'), ('apag', 'Matrícula foi apagada')], max_length=4, verbose_name='Atividade da matrícula')),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_matricula', to='mentorias.matriculaalunomentoria', verbose_name='Matrícula relacionada')),
            ],
        ),
    ]
