# Generated by Django 4.2.1 on 2023-05-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0028_remove_alunos_situacao_matricula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculaalunomentoria',
            unique_together={('mentoria', 'aluno')},
        ),
    ]
