# Generated by Django 4.0 on 2023-08-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0029_alter_alunos_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaalunomentoria',
            name='encerrada',
        ),
        migrations.AddField(
            model_name='matriculaalunomentoria',
            name='inativa',
            field=models.BooleanField(default=False, verbose_name='Ativa ou inativa'),
        ),
    ]
