# Generated by Django 4.2.1 on 2023-05-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0031_alter_alunos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculaalunomentoria',
            old_name='created',
            new_name='criada_em',
        ),
    ]
