# Generated by Django 4.2.1 on 2023-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0032_rename_created_matriculaalunomentoria_criada_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulados',
            old_name='pontuação',
            new_name='pontuacao',
        ),
        migrations.AddField(
            model_name='simulados',
            name='controle',
            field=models.TextField(blank=True, help_text='Anotações da Mentoria para seu controle. Apenas você terá acesso a este conteúdo.', null=True, verbose_name='Anotações da mentoria'),
        ),
    ]
