# Generated by Django 4.0 on 2023-09-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0032_remove_registrosmentor_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaalunomentoria',
            name='inativa',
        ),
        migrations.RemoveField(
            model_name='registrosmentor',
            name='log_matricula_inativa',
        ),
        migrations.AddField(
            model_name='matriculaalunomentoria',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Está ativa'),
        ),
        migrations.AddField(
            model_name='registrosmentor',
            name='log_matricula_ativa',
            field=models.BooleanField(null=True, verbose_name='Ativa'),
        ),
    ]
