# Generated by Django 4.0 on 2023-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0033_remove_matriculaalunomentoria_inativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosmentor',
            name='data_resposta',
            field=models.DateTimeField(null=True, verbose_name='Data da resposta do simulado'),
        ),
        migrations.AddField(
            model_name='registrosmentor',
            name='log_simulado',
            field=models.IntegerField(null=True, verbose_name='Número do simulado'),
        ),
        migrations.AlterField(
            model_name='registrosmentor',
            name='atividade',
            field=models.CharField(choices=[('cria', 'Matrícula foi criada'), ('ence', 'Matrícula foi encerrada'), ('alte', 'Matrícula foi alterada'), ('apag', 'Matrícula foi apagada'), ('resp', 'Resposta no simulado')], max_length=4, verbose_name='Atividade da matrícula'),
        ),
    ]
