# Generated by Django 4.2.1 on 2023-05-29 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0034_alter_simulados_instrucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulados',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 5, 29, 23, 45, 41, 565317, tzinfo=datetime.timezone.utc), verbose_name='Criado'),
            preserve_default=False,
        ),
    ]
