# Generated by Django 4.2.3 on 2023-09-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0034_registrosmentor_data_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='telefone_aluno',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone do Aluno'),
        ),
    ]
