# Generated by Django 4.2.3 on 2023-09-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0035_alter_alunos_telefone_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='email_aluno',
            field=models.EmailField(max_length=254, verbose_name='Email do Aluno'),
        ),
    ]
