# Generated by Django 4.2.3 on 2024-01-20 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0036_alter_alunos_email_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoria',
            name='encerra_em',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fim da mentoria:'),
        ),
    ]
