# Generated by Django 4.2.1 on 2023-05-30 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0036_remove_materias_mentor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='criada_em',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Criada em'),
        ),
    ]
