# Generated by Django 4.2.3 on 2024-01-20 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0037_mentoria_encerra_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoria',
            name='periodo_duracao',
            field=models.SmallIntegerField(blank=True, default=6, help_text='Novas matrículas na mentoria terão esta duração por padrão.', null=True, verbose_name='Período de duração de uma matrícula (em meses).'),
        ),
        migrations.AlterField(
            model_name='mentoria',
            name='encerra_em',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Todas as matrículas desta mentoria durarão até no máximo esta data.', verbose_name='Fim da mentoria:'),
        ),
    ]
