# Generated by Django 4.2.1 on 2023-05-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0037_materias_criada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='controle',
            field=models.TextField(blank=True, help_text='Anotações da matéria para seu controle. Apenas você terá acesso a este conteúdo.', null=True, verbose_name='Anotações da matéria'),
        ),
    ]
