# Generated by Django 4.2.3 on 2024-01-20 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0038_mentoria_periodo_duracao_alter_mentoria_encerra_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoria',
            name='encerra_em',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Todas as matrículas desta mentoria durarão até no máximo esta data.', verbose_name='Fim da mentoria:'),
        ),
    ]
