# Generated by Django 4.2.1 on 2023-05-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0038_materias_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulados',
            name='gabarito',
            field=models.JSONField(blank=True, null=True, verbose_name='Respostas do Gabarito'),
        ),
    ]
