# Generated by Django 4.2.3 on 2024-01-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0040_alter_matriculaalunomentoria_encerra_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosmentor',
            name='log_matricula_encerra_em',
            field=models.DateField(null=True, verbose_name='Data encerramento da matrícula'),
        ),
    ]
