# Generated by Django 4.2.3 on 2024-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0041_alter_registrosmentor_log_matricula_encerra_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaalunomentoria',
            name='data_desativada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora que foi desativada'),
        ),
    ]
