# Generated by Django 4.2.1 on 2023-06-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0042_alter_materias_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArquivosMentor',
        ),
    ]
