# Generated by Django 4.2.3 on 2024-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0042_matriculaalunomentoria_data_desativada'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaalunomentoria',
            name='data_reativada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora em que foi reativada'),
        ),
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='data_desativada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora em que foi desativada'),
        ),
        migrations.AlterField(
            model_name='registrosmentor',
            name='atividade',
            field=models.CharField(choices=[('cria', 'Matrícula foi criada'), ('ence', 'Matrícula foi encerrada'), ('alte', 'Matrícula foi alterada'), ('desa', 'Matrícula foi desativada'), ('reat', 'Matrícula foi reativada'), ('apag', 'Matrícula foi apagada'), ('resp', 'Resposta no simulado')], max_length=4, verbose_name='Atividade da matrícula'),
        ),
    ]
