# Generated by Django 4.2.3 on 2024-01-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0044_alter_matriculaalunomentoria_data_desativada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='data_desativada',
            field=models.DateField(blank=True, null=True, verbose_name='Data em que foi desativada'),
        ),
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='data_reativada',
            field=models.DateField(blank=True, null=True, verbose_name='Data em que foi reativada'),
        ),
    ]
