# Generated by Django 4.2.1 on 2023-06-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0044_linksexternos_mentorias_links_externos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksexternos',
            name='descricao',
            field=models.CharField(blank=True, help_text='Escreva uma breve descrição, caso você deseja comunicar-se com o aluno à respeito do link.', max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='linksexternos',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo do link'),
        ),
    ]
