# Generated by Django 4.2.3 on 2024-01-24 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0045_alter_matriculaalunomentoria_data_desativada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='criada_em',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da matrícula'),
        ),
    ]
