# Generated by Django 4.2.3 on 2024-01-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0046_alter_matriculaalunomentoria_criada_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='student_user',
        ),
    ]
