# Generated by Django 4.2.1 on 2023-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0047_aplicacaosimulado_data_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorias',
            name='simulados_mentoria',
            field=models.ManyToManyField(blank=True, to='mentorias.aplicacaosimulado'),
        ),
    ]
