# Generated by Django 4.2.3 on 2024-01-29 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorias', '0047_remove_alunos_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMatrículaAlunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Aluno')),
                ('email_aluno', models.EmailField(max_length=254, verbose_name='Email do Aluno')),
                ('telefone_aluno', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone do Aluno')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do cadastramento do aluno')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da confirmação')),
                ('mentor_a_confirmar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_a_confirmar', to=settings.AUTH_USER_MODEL)),
                ('mentoria_pre_matriculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_matriculas', to='mentorias.mentoria')),
            ],
            options={
                'ordering': ['nome_aluno', '-pk'],
            },
        ),
    ]
