# Generated by Django 4.2.3 on 2024-01-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0048_prematrículaalunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prematrículaalunos',
            name='mentor_a_confirmar',
        ),
    ]
