# Generated by Django 4.2.1 on 2023-06-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0049_aplicacaosimulado_criada_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacaosimulado',
            name='respostas_alunos',
            field=models.JSONField(blank=True, null=True, verbose_name='Respostas do Aluno'),
        ),
    ]
