# Generated by Django 4.2.3 on 2024-01-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0049_remove_prematrículaalunos_mentor_a_confirmar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosmentor',
            name='log_data_desativada',
            field=models.DateField(null=True, verbose_name='Data em que foi desativada'),
        ),
        migrations.AddField(
            model_name='registrosmentor',
            name='log_data_reativada',
            field=models.DateField(null=True, verbose_name='Data em que foi reativada'),
        ),
    ]
