# Generated by Django 4.2.3 on 2024-02-05 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0051_loginalunos_alter_registrosmentor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='login_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.loginalunos', verbose_name='Login relacionado ao aluno'),
        ),
        migrations.AlterField(
            model_name='loginalunos',
            name='criada_em_aluno_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 10, 7, 24, 860686), verbose_name='Criada em:'),
        ),
    ]
