# Generated by Django 4.2.1 on 2023-06-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0051_aplicacaosimulado_aplicacao_agendada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacaosimulado',
            options={'ordering': ['-criada_em']},
        ),
        migrations.AddField(
            model_name='mentorias',
            name='resumo_mentoria',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Resumo'),
        ),
    ]
