# Generated by Django 4.2.1 on 2023-06-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0053_mentorias_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='situacao_aluno',
            field=models.BooleanField(default=True, help_text='Se é aluno atual, ou ex-aluno.', verbose_name='Situação do aluno'),
        ),
    ]
