# Generated by Django 4.2.1 on 2023-06-16 23:43

from django.db import migrations, models
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0060_aplicacaosimulado_senha_de_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacaosimulado',
            name='senha_de_acesso',
        ),
        migrations.AddField(
            model_name='aplicacaosimulado',
            name='senha_do_simulado',
            field=models.CharField(blank=True, default=mentorias.models.get_random_string, max_length=6, null=True, verbose_name='Senha do simulado'),
        ),
    ]
