# Generated by Django 4.2.3 on 2024-02-08 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0060_alter_loginalunos_criada_em_aluno_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginalunos',
            name='criada_em_aluno_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 20, 8, 45, 319345), verbose_name='Criada em:'),
        ),
        migrations.AlterField(
            model_name='mentoria',
            name='periodo_duracao',
            field=models.SmallIntegerField(blank=True, default=6, help_text='Prazo de encerramento da matrícula pode ser alterado no painel próprio da matrícula.', null=True, verbose_name='Período de trabalho com uma matrícula(aluno individual), em meses.'),
        ),
    ]
