# Generated by Django 4.2.1 on 2023-06-16 23:45

from django.db import migrations, models
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0061_remove_aplicacaosimulado_senha_de_acesso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacaosimulado',
            name='senha_do_simulado',
        ),
        migrations.AddField(
            model_name='aplicacaosimulado',
            name='senha_do_aluno',
            field=models.CharField(blank=True, default=mentorias.models.get_random_string, max_length=6, null=True, verbose_name='Senha para acesso'),
        ),
    ]
