# Generated by Django 4.2.3 on 2024-02-09 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0063_alter_loginalunos_criada_em_aluno_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginalunos',
            name='email_aluno_login_original',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de login'),
        ),
        migrations.AlterField(
            model_name='loginalunos',
            name='criada_em_aluno_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 10, 55, 48, 719334), verbose_name='Criada em:'),
        ),
    ]
