# Generated by Django 4.2.1 on 2023-07-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0065_matriculaalunomentoria_senha_do_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulados',
            name='mentor_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentorias',
            name='arquivos_mentoria',
            field=models.ManyToManyField(blank=True, help_text='Arquivos de uma mentoria são arquivos disponíveis aos estudantes \t\t\t\tque fizerem parte da mentoria.', to='mentorias.arquivosmentoria'),
        ),
    ]
