# Generated by Django 4.2.3 on 2024-02-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0009_alter_policyrules_title'),
        ('mentorias', '0067_alter_loginalunos_criada_em_aluno_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaAceitaPorAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('profile_id', models.IntegerField(verbose_name='Id do usuário')),
                ('acept_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da aceitação')),
                ('login_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.loginalunos', verbose_name='Login do aluno')),
                ('politica_aceita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicas.policyrules', verbose_name='Política de Privacidade')),
            ],
        ),
        migrations.DeleteModel(
            name='TermosAceitosAluno',
        ),
    ]
