# Generated by Django 4.2.3 on 2024-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0068_politicaaceitaporaluno_delete_termosaceitosaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoria',
            name='encerra_em',
            field=models.DateField(blank=True, help_text='Todas as matrículas desta mentoria durarão até no máximo esta data.', null=True, verbose_name='Fim da mentoria:'),
        ),
    ]
