# Generated by Django 4.2.1 on 2023-07-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0069_rename_arquivos_mentoria_mentoria_arquivos_da_mentoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aplicacaosimulado',
            unique_together=set(),
        ),
    ]
