# Generated by Django 4.2.3 on 2024-02-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0069_alter_mentoria_encerra_em'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_Mentoria_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_Alunos_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_LoginAlunos_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_PreMatrículaAlunos_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_MatriculaAlunoMentoria_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_Simulados_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_Materias_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_ArquivosMentoria_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_LinksExternos_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_AplicacaoSimulado_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_RegistrosMentor_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(
            'ALTER SEQUENCE mentorias_PoliticaAceitaPorAluno_id_seq RESTART WITH 1111;')        
    ]