# Generated by Django 4.2.1 on 2023-05-21 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremailcheck',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='user_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Usuário desde'),
        ),
        migrations.AlterField(
            model_name='useremailcheck',
            name='confirmed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da confimação'),
        ),
        migrations.AlterField(
            model_name='useremailcheck',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data do email'),
        ),
    ]
