# Generated by Django 4.2.1 on 2023-05-21 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_rename_ferramenta_favorita_preferences_login_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data da remoçao do usuário'),
        ),
    ]
