# Generated by Django 4.2.1 on 2023-07-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_preferences_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='user',
            new_name='usuario',
        ),
    ]
