# Generated by Django 4.0 on 2023-09-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_rua', models.CharField(max_length=30, verbose_name='Rua')),
                ('endereco_numero', models.CharField(max_length=10, verbose_name='Número')),
                ('endereco_complemento', models.CharField(help_text='Ex: Apto 601, ou Lote 40', max_length=30, verbose_name='Complemento')),
                ('endereco_bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('endereco_cep', models.CharField(max_length=30, verbose_name='CEP')),
                ('endereco_resumido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Resumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser', verbose_name='Endereço de cobrança')),
            ],
        ),
    ]
