# Generated by Django 4.0 on 2023-09-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_remove_customuser_cnpj_faturamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecocobranca',
            name='telefone1',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone de contato 1'),
        ),
        migrations.AddField(
            model_name='enderecocobranca',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato 2'),
        ),
    ]
