# Generated by Django 4.2.3 on 2023-09-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_enderecocobranca_telefone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_bairro',
            field=models.CharField(max_length=30, null=True, verbose_name='Bairro*'),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_cep',
            field=models.CharField(max_length=30, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_cidade',
            field=models.CharField(max_length=30, null=True, verbose_name='Cidade*'),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_complemento',
            field=models.CharField(help_text='Ex: Apto 601, ou Lote 40', max_length=30, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_estado',
            field=models.CharField(max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_numero',
            field=models.CharField(max_length=10, null=True, verbose_name='Número*'),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_rua',
            field=models.CharField(max_length=30, null=True, verbose_name='Rua*'),
        ),
        migrations.AlterField(
            model_name='enderecocobranca',
            name='telefone1',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone de contato 1*'),
        ),
    ]
