# Generated by Django 4.2.3 on 2024-02-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_alter_useremailcheck_date'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE usuarios_CustomUser_id_seq RESTART WITH 10025;'
        )
    ]
