# Generated by Django 4.2.3 on 2024-02-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_auto_20240202_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome_apresentacao',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome de apresentação'),
        ),
    ]
