# Generated by Django 4.2.3 on 2024-02-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_customuser_nome_apresentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nome_apresentacao',
            field=models.CharField(help_text='*Nome para se apresentar ao aluno', max_length=50, null=True, verbose_name='Nome de apresentação'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='*Username para login', max_length=50, unique=True, verbose_name='Usuário'),
        ),
    ]
