# Generated by Django 4.0 on 2023-09-06 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0019_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturasMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data assinatura')),
                ('encerra_em', models.DateField(blank=True, null=True, verbose_name='Encerra em')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('usuario_cpf', models.CharField(max_length=20, verbose_name='CPF/CNPJ do usuário')),
                ('log_usuario_pk', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id do usuário')),
                ('log_usuario_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário')),
                ('log_usuario_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do usuário')),
                ('meses_desconto_restante', models.IntegerField(default=0, verbose_name='Meses com desconto')),
                ('meses_isencao_restante', models.IntegerField(default=1, verbose_name='Meses com isencao')),
                ('limite_matriculas', models.IntegerField(verbose_name='Limite de matrículas')),
            ],
        ),
        migrations.CreateModel(
            name='Descontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_desconto', models.FloatField(default=0.0)),
                ('meses_isencao', models.SmallIntegerField(default=1, verbose_name='Meses de isenção')),
                ('meses_desconto', models.SmallIntegerField(default=12, verbose_name='Meses de desconto')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nome comercial do desconto')),
                ('abreviatura', models.CharField(blank=True, help_text='Escreva uma abreviatura de até 10 caracteres.', max_length=10, null=True, verbose_name='Abreviatura')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('desconto', models.FloatField(default=0)),
                ('encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Encerramento')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('log_criado_por_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('log_criado_por_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('log_criado_por_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.customuser', verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='PrecosAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nome comercial')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('ativo', models.BooleanField(default=False, verbose_name='Em uso')),
                ('preco', models.FloatField()),
                ('log_criado_por_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('log_criado_por_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('log_criado_por_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('precos', models.JSONField(verbose_name='Preços')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.customuser', verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='OfertasPlanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da oferta')),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data cadastro')),
                ('encerra_em', models.DateTimeField(blank=True, null=True, verbose_name='Data do encerramento')),
                ('ativa', models.BooleanField(default=False, verbose_name='Ativa')),
                ('log_criado_por_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('log_criado_por_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('log_criado_por_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.customuser', verbose_name='Criado por')),
                ('desconto_incluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_desconto', to='assinaturas.descontos')),
                ('preco_ofetado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assinaturas.precosassinatura', verbose_name='Preço ofertado')),
            ],
        ),
        migrations.CreateModel(
            name='FaturasMentores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_usuario_pk', models.IntegerField(null=True, verbose_name='Usuario pk')),
                ('log_usuario_email', models.EmailField(max_length=254, null=True, verbose_name='Email do usuário')),
                ('log_usuario_nome', models.CharField(max_length=200, null=True, verbose_name='Nome do usuário')),
                ('quantidade_matriculas', models.IntegerField(default=0, verbose_name='Quantidade de matrículas ativas')),
                ('vencimento', models.DateField(verbose_name='Data do vencimento')),
                ('usuario_cpf', models.CharField(max_length=20, verbose_name='CPF/CNPJ do usuário')),
                ('valor_total', models.FloatField(verbose_name='Valor total')),
                ('desconto_aplicado', models.FloatField(default=0.0, verbose_name='Desconto aplicado')),
                ('mes_isento', models.BooleanField(default=False, verbose_name='Mês de isenção')),
                ('total_a_pagar', models.FloatField(verbose_name='Valor a pagar')),
                ('foi_paga', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('numero_transacao', models.CharField(max_length=30, null=True, verbose_name='Transação')),
                ('assinatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatura_assinatura', to='assinaturas.assinaturasmentor', verbose_name='Assinatura relacionada')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.customuser', verbose_name='Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='assinaturasmentor',
            name='oferta_contratada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinatura_oferta', to='assinaturas.ofertasplanos', verbose_name='Oferta contratada'),
        ),
        migrations.AddField(
            model_name='assinaturasmentor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.customuser', verbose_name='Mentor'),
        ),
    ]
