# Generated by Django 4.0 on 2023-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_remove_assinaturasmentor_limite_matriculas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturasmentor',
            name='usuario_endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço para cobrança'),
        ),
    ]
