# Generated by Django 4.0 on 2023-09-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_enderecocobranca'),
        ('assinaturas', '0003_assinaturasmentor_usuario_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinaturasmentor',
            name='usuario_endereco',
        ),
        migrations.AddField(
            model_name='assinaturasmentor',
            name='endereco_cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.enderecocobranca', verbose_name='Endereço para cobrança'),
        ),
    ]
