# Generated by Django 4.0 on 2023-09-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0005_assinaturasmentor_log_endereco_resumido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinaturasmentor',
            old_name='usuario',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='faturasmentores',
            old_name='log_usuario_email',
            new_name='log_mentor_email',
        ),
        migrations.RenameField(
            model_name='faturasmentores',
            old_name='log_usuario_nome',
            new_name='log_mentor_nome',
        ),
        migrations.RenameField(
            model_name='faturasmentores',
            old_name='usuario',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='faturasmentores',
            old_name='usuario_cpf',
            new_name='mentor_cpf',
        ),
        migrations.RemoveField(
            model_name='faturasmentores',
            name='log_usuario_pk',
        ),
        migrations.AddField(
            model_name='faturasmentores',
            name='log_mentor_pk',
            field=models.IntegerField(null=True, verbose_name='Mentor pk'),
        ),
    ]
