# Generated by Django 4.0 on 2023-09-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0006_rename_usuario_assinaturasmentor_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturasmentor',
            name='log_precos_contratados',
            field=models.JSONField(null=True, verbose_name='Preços contratados'),
        ),
    ]
