# Generated by Django 4.0 on 2023-09-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0007_assinaturasmentor_log_precos_contratados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinaturasmentor',
            old_name='usuario_cpf',
            new_name='mentor_cpf',
        ),
    ]
