# Generated by Django 4.0 on 2023-09-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0008_rename_usuario_cpf_assinaturasmentor_mentor_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinaturasmentor',
            old_name='mentor_cpf',
            new_name='log_mentor_cpf',
        ),
    ]
