# Generated by Django 4.0 on 2023-09-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0009_rename_mentor_cpf_assinaturasmentor_log_mentor_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinaturasmentor',
            name='log_meses_desconto_restante',
        ),
        migrations.RemoveField(
            model_name='descontos',
            name='meses_desconto',
        ),
    ]
