# Generated by Django 4.0 on 2023-09-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0012_alter_faturasmentores_mentor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturasmentor',
            name='log_mentor_cpf',
            field=models.CharField(max_length=20, null=True, verbose_name='CPF/CNPJ do usuário'),
        ),
    ]
