# Generated by Django 4.0 on 2023-09-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0013_alter_assinaturasmentor_log_mentor_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturasmentores',
            name='gastos_no_mes',
            field=models.FloatField(default=0, verbose_name='Gastos no mês'),
        ),
    ]
