# Generated by Django 4.0 on 2023-09-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0015_faturasmentores_mes_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faturasmentores',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='assinaturasmentor',
            name='renovacao_automatica',
            field=models.BooleanField(default=True, verbose_name='Renovação automática habilitada'),
        ),
    ]
