# Generated by Django 4.0 on 2023-09-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0016_alter_faturasmentores_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertasplanos',
            name='tipo',
            field=models.SmallIntegerField(default=1, verbose_name='Tipo de oferta'),
        ),
    ]
