# Generated by Django 4.2.3 on 2023-09-18 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assinaturas', '0019_assinaturasmentor_log_condicoes_contratadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracoesTermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criaou ou modificou o termo')),
                ('termo_user_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criaou ou modificou o termo')),
                ('termos_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título da política')),
                ('termo_status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado do termo(ativa ou não)')),
                ('termo_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo do termo')),
                ('termo_pkey', models.IntegerField(blank=True, null=True, verbose_name='Id do termo')),
                ('mod_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da modificação')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ação realizada')),
            ],
            options={
                'verbose_name_plural': 'Modificações nos termos',
            },
        ),
        migrations.CreateModel(
            name='TermosDeUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Título do termo')),
                ('text', models.TextField(verbose_name='Conteúdo do termo')),
                ('begin_date', models.DateTimeField(verbose_name='Data do início da vigência')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do fim da vigência')),
                ('active', models.BooleanField(default=False, verbose_name='Regra está vigente(regra em uso)')),
                ('criada_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da criação')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criou a regra')),
                ('termo_user_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criou a regra')),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='pt-br', max_length=5, verbose_name='Lingua')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que criou a regra')),
            ],
            options={
                'verbose_name_plural': 'Termos',
            },
        ),
        migrations.CreateModel(
            name='TermosAceitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('profile_id', models.IntegerField(verbose_name='Id do usuário')),
                ('acept_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da aceitação')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assinaturas.termosdeuso', verbose_name='Termos de Uso')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
