# Generated by Django 4.2.3 on 2023-09-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0021_rename_title_termosdeuso_termo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alteracoestermos',
            old_name='termos_title',
            new_name='termo_title',
        ),
    ]
