# Generated by Django 4.2.3 on 2023-09-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0023_ofertasplanos_pequeno_anuncio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertasplanos',
            old_name='preco_ofetado',
            new_name='preco_ofertado',
        ),
    ]
