# Generated by Django 4.2.3 on 2024-01-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0026_remove_assinaturasmentor_endereco_cobranca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturasmentor',
            name='log_mentor_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ do usuário'),
        ),
        migrations.AlterField(
            model_name='assinaturasmentor',
            name='log_precos_contratados',
            field=models.JSONField(blank=True, null=True, verbose_name='Preços contratados'),
        ),
        migrations.AlterField(
            model_name='assinaturasmentor',
            name='log_telefone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone de contato com o DDD*'),
        ),
    ]
