# Generated by Django 4.2.3 on 2024-01-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0027_alter_assinaturasmentor_log_mentor_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturasmentor',
            name='resumo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resumo da oferta!'),
        ),
    ]
