# Generated by Django 4.2.3 on 2024-01-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0028_assinaturasmentor_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinaturasmentor',
            name='perfil_cobranca',
        ),
    ]
