# Generated by Django 4.2.3 on 2024-01-25 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assinaturas', '0029_remove_assinaturasmentor_perfil_cobranca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturasmentor',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_mentor', to=settings.AUTH_USER_MODEL, verbose_name='Mentor'),
        ),
    ]
