# Generated by Django 4.2.3 on 2024-01-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0030_alter_assinaturasmentor_mentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assinaturasmentor',
            options={'ordering': ['encerra_em']},
        ),
        migrations.AddField(
            model_name='assinaturasmentor',
            name='inicia_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Inicia vigência em'),
        ),
    ]
