# Generated by Django 4.2.3 on 2024-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0031_alter_assinaturasmentor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertasplanos',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='ofertasplanos',
            name='inicia_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Início da vigência'),
        ),
        migrations.AddField(
            model_name='ofertasplanos',
            name='promocional',
            field=models.BooleanField(default=False, verbose_name='É promocional'),
        ),
    ]
