# Generated by Django 4.2.3 on 2024-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0032_alter_ofertasplanos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertasplanos',
            name='encerra_em',
            field=models.DateField(blank=True, null=True, verbose_name='Data do encerramento'),
        ),
    ]
