# Generated by Django 4.2.3 on 2024-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0033_alter_ofertasplanos_encerra_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertasplanos',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
