# Generated by Django 4.2.3 on 2024-02-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0056_alter_loginalunos_criada_em_aluno_login'),
        ('assinaturas', '0034_alter_ofertasplanos_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='termosaceitos',
            name='login_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.loginalunos', verbose_name='Login do aluno'),
        ),
    ]
