# Generated by Django 4.2.3 on 2024-02-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0035_termosaceitos_login_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termosaceitos',
            name='login_aluno',
        ),
        migrations.AddField(
            model_name='termosdeuso',
            name='publico_allvo',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('aluno', 'Aluno')], default='mentor', max_length=10, null=True, verbose_name='Público alvo do termo'),
        ),
    ]
