# Generated by Django 4.2.3 on 2024-02-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0036_remove_termosaceitos_login_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertasplanos',
            name='desconto_incluido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferta_desconto', to='assinaturas.descontos'),
        ),
    ]
