# Generated by Django 4.2.3 on 2024-02-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0037_alter_ofertasplanos_desconto_incluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descontos',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Escreva uma abreviatura de até 50 caracteres.', max_length=50, null=True, verbose_name='Abreviatura'),
        ),
    ]
