# Generated by Django 4.2.3 on 2024-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0038_alter_descontos_abreviatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descontos',
            name='abreviatura',
        ),
        migrations.AddField(
            model_name='assinaturasmentor',
            name='resumo_desconto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resumo do desconto incluído'),
        ),
        migrations.AddField(
            model_name='descontos',
            name='resumo_desconto',
            field=models.CharField(blank=True, help_text='Escreva um resumo de até 50 caracteres.', max_length=50, null=True, verbose_name='Resumo do desconto'),
        ),
        migrations.AlterField(
            model_name='assinaturasmentor',
            name='resumo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resumo da oferta'),
        ),
    ]
