# Generated by Django 4.2.3 on 2024-02-18 15:33

import assinaturas.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0040_alter_descontos_resumo_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='termosdeuso',
            name='arquivo_termo',
            field=models.FileField(help_text='Insira arquivo em .pdf de até 10MB de tamanho.', null=True, upload_to=assinaturas.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), assinaturas.models.file_size], verbose_name='Arquvio do termo'),
        ),
    ]
