# Generated by Django 4.2.3 on 2024-02-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0041_termosdeuso_arquivo_termo'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE assinaturas_AssinaturasMentor_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(            
            'ALTER SEQUENCE assinaturas_FaturasMentores_id_seq RESTART WITH 1122;'),
        migrations.RunSQL(
            'ALTER SEQUENCE assinaturas_TermosAceitos_id_seq RESTART WITH 1133;'
        )
    ]
