# Generated by Django 4.2.1 on 2023-05-24 02:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorias', '0005_mentorias_remove_turmas_programa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivosaluno',
            name='titulo_arquivo',
        ),
        migrations.RemoveField(
            model_name='arquivosmentoria',
            name='titulo_arquivo',
        ),
        migrations.AddField(
            model_name='arquivosaluno',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.alunos'),
        ),
        migrations.AddField(
            model_name='arquivosmentoria',
            name='mentoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.mentorias'),
        ),
        migrations.AlterField(
            model_name='simulados',
            name='data_aplicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data prevista para aplicação'),
        ),
        migrations.CreateModel(
            name='ArquivosMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Criado por:')),
                ('titulo_arquivo', models.CharField(max_length=50, verbose_name='Nome do arquivo')),
                ('arquivo_mentor', models.FileField(help_text='Insira arquivo em .pdf de até 5MB de tamanho.', upload_to=mentorias.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), mentorias.models.file_size], verbose_name='Arquvio')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='arquivosaluno',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.arquivosmentor'),
        ),
        migrations.AlterField(
            model_name='arquivosmentoria',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.arquivosmentor'),
        ),
    ]
