# Generated by Django 4.2.1 on 2023-05-24 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorias', '0006_remove_arquivosaluno_titulo_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabaritos',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gabaritos',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materias',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
