# Generated by Django 4.2.1 on 2023-05-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0007_gabaritos_mentor_gabaritos_mentor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulados',
            old_name='gabarito',
            new_name='gabarito_model',
        ),
    ]
