# Generated by Django 4.2.1 on 2023-05-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0008_rename_gabarito_simulados_gabarito_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulados',
            name='gabarito',
            field=models.JSONField(null=True, verbose_name='Respostas do Gabarito'),
        ),
        migrations.AddField(
            model_name='simulados',
            name='pontuação',
            field=models.PositiveIntegerField(null=True, verbose_name='Pontuação máxima'),
        ),
    ]
