# Generated by Django 4.2.1 on 2023-05-25 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorias', '0011_arquivosmentoria_arquivo_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosmentoria',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
