# Generated by Django 4.2.1 on 2023-05-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0012_arquivosmentoria_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='arquivos_aluno',
            field=models.ManyToManyField(help_text='Arquivos de um Aluno são arquivos disponíveis ao estudante selecionado.', null=True, to='mentorias.arquivosaluno'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='nivel_preparo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Avançado')], default=1, verbose_name='Nível de preparo para o objetivo final.'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='simulados_realizados',
            field=models.ManyToManyField(help_text='Simulados que os alunos devem fazer.', null=True, to='mentorias.simulados'),
        ),
    ]
