# Generated by Django 4.2.1 on 2023-05-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0013_alter_alunos_arquivos_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='turma_matriculada',
            field=models.ManyToManyField(null=True, to='mentorias.turmas', verbose_name='Turma matriculada'),
        ),
    ]
