# Generated by Django 4.2.1 on 2023-05-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0019_rename_aluno_arquivosaluno_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosaluno',
            name='email_aluno',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Aluno'),
        ),
    ]
