# Generated by Django 4.2.1 on 2023-05-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0025_alter_alunos_situacao_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaAlunoMentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data da matrícula')),
                ('encerra', models.DateField(blank=True, null=True, verbose_name='Encerramento mentoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='simulados',
            name='gabarito_model',
        ),
        migrations.AlterField(
            model_name='alunos',
            name='situacao_aluno',
            field=models.CharField(choices=[('at', 'Ativo'), ('ex', 'Ex-aluno')], default='at', help_text='Se é aluno atual, ou ex-aluno.', max_length=2, verbose_name='Situação'),
        ),
        migrations.DeleteModel(
            name='Gabaritos',
        ),
        migrations.AddField(
            model_name='matriculaalunomentoria',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorias.alunos'),
        ),
        migrations.AddField(
            model_name='matriculaalunomentoria',
            name='mentoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorias.mentorias'),
        ),
    ]
