# Generated by Django 4.2.1 on 2023-05-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0027_rename_encerra_matriculaalunomentoria_encerra_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='situacao_matricula',
        ),
    ]
