# Generated by Django 4.2.1 on 2023-05-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0030_alter_matriculaalunomentoria_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunos',
            options={'ordering': ['nome_aluno', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='matriculaalunomentoria',
            options={'ordering': ['aluno']},
        ),
        migrations.RenameField(
            model_name='alunos',
            old_name='data_cadastro',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='mentorias',
            old_name='data_cadastro',
            new_name='criada_em',
        ),
        migrations.AlterField(
            model_name='mentorias',
            name='matriculas',
            field=models.ManyToManyField(blank=True, to='mentorias.matriculaalunomentoria'),
        ),
    ]
