# Generated by Django 4.2.1 on 2023-05-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0033_rename_pontuação_simulados_pontuacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulados',
            name='instrucao',
            field=models.TextField(blank=True, help_text='Se desejar, seus alunos poderão receber instruções para a realização do simulado.', null=True, verbose_name='Instruções ao aluno que fará o simulado'),
        ),
    ]
