# Generated by Django 4.2.1 on 2023-05-30 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0035_simulados_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='mentor_name',
        ),
    ]
