# Generated by Django 4.2.1 on 2023-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0040_mentorias_simulados_mentoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulados',
            name='questao_qtd',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade de questões no simulado'),
        ),
        migrations.AlterField(
            model_name='simulados',
            name='questao_tipo',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'A-D'), (2, 'A-E'), (3, 'Certo/Errado')], null=True, verbose_name='Tipo de questões'),
        ),
    ]
