# Generated by Django 4.2.1 on 2023-06-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0041_alter_simulados_questao_qtd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materias',
            options={'ordering': ['titulo']},
        ),
        migrations.RemoveField(
            model_name='arquivosmentoria',
            name='arquivo',
        ),
    ]
