# Generated by Django 4.2.1 on 2023-06-04 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0045_alter_linksexternos_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas_alunos', models.JSONField(verbose_name='Respostas do Aluno')),
                ('aluno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplicacao_aluno', to='mentorias.alunos')),
                ('simulado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplicacao_simulado', to='mentorias.simulados')),
            ],
            options={
                'unique_together': {('aluno', 'simulado')},
            },
        ),
    ]
