# Generated by Django 4.2.1 on 2023-06-04 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0046_aplicacaosimulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacaosimulado',
            name='data_resposta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da resposta'),
        ),
    ]
