# Generated by Django 4.2.1 on 2023-06-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0052_alter_aplicacaosimulado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorias',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
