# Generated by Django 4.2.1 on 2023-06-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0054_alter_alunos_situacao_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='situacao_aluno',
            field=models.CharField(choices=[('at', 'Ativo'), ('ex', 'Ex-aluno')], default='at', help_text='Se é aluno atual, ou ex-aluno.', max_length=2, verbose_name='Situação'),
        ),
    ]
