# Generated by Django 4.2.1 on 2023-06-16 01:17

from django.db import migrations, models
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0059_alter_planosassinatura_criado_por_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacaosimulado',
            name='senha_de_acesso',
            field=models.CharField(blank=True, default=mentorias.models.get_random_string, max_length=6, null=True, verbose_name='Senha da aplicação'),
        ),
    ]
