# Generated by Django 4.2.1 on 2023-06-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0062_remove_aplicacaosimulado_senha_do_simulado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacaosimulado',
            name='respostas_alunos',
        ),
        migrations.AddField(
            model_name='aplicacaosimulado',
            name='resposta_alunos',
            field=models.JSONField(blank=True, null=True, verbose_name='Resposta do Aluno'),
        ),
    ]
