# Generated by Django 4.2.1 on 2023-07-12 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorias', '0066_simulados_mentor_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacaosimulado',
            name='simulado_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo do simulado'),
        ),
        migrations.AddField(
            model_name='mentorias',
            name='username_mentor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Username do Mentor'),
        ),
        migrations.AlterField(
            model_name='aplicacaosimulado',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacao_aluno', to='mentorias.alunos'),
        ),
        migrations.AlterField(
            model_name='aplicacaosimulado',
            name='simulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicacao_simulado', to='mentorias.simulados'),
        ),
        migrations.AlterField(
            model_name='mentorias',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simulados',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título do simulado'),
        ),
    ]
