# Generated by Django 4.2.1 on 2023-07-15 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorias', '0067_aplicacaosimulado_simulado_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira um título para a mentoria.', max_length=100, verbose_name='Titulo da mentoria')),
                ('criada_em', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data criação:')),
                ('controle', models.TextField(blank=True, help_text='Anotações da Mentoria para seu controle. Apenas você terá acesso a este conteúdo.', null=True, verbose_name='Anotações da mentoria')),
                ('resumo_mentoria', models.TextField(blank=True, help_text='Se desejar, escreva um texto de apresentação desta mentoria ao estudante.', max_length=300, null=True, verbose_name='Resumo')),
                ('etapas', models.JSONField(blank=True, null=True, verbose_name='Etapas da mentoria')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('username_mentor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username do Mentor')),
                ('arquivos_mentoria', models.ManyToManyField(blank=True, help_text='Arquivos de uma mentoria são arquivos disponíveis aos estudantes \t\t\t\tque fizerem parte da mentoria.', related_name='arquivos_da_mentoria', to='mentorias.arquivosmentoria')),
                ('links_externos', models.ManyToManyField(blank=True, to='mentorias.linksexternos')),
                ('matriculas', models.ManyToManyField(blank=True, to='mentorias.matriculaalunomentoria')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('simulados_mentoria', models.ManyToManyField(blank=True, to='mentorias.aplicacaosimulado')),
            ],
        ),
        migrations.AlterField(
            model_name='arquivosmentoria',
            name='mentoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.mentoria'),
        ),
        migrations.DeleteModel(
            name='Mentorias',
        ),
    ]
