# Generated by Django 4.2.1 on 2023-07-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0068_mentoria_alter_arquivosmentoria_mentoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoria',
            old_name='arquivos_mentoria',
            new_name='arquivos_da_mentoria',
        ),
    ]
