# Generated by Django 4.2.1 on 2023-07-17 00:50

from django.db import migrations, models
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0074_alter_aplicacaosimulado_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacaosimulado',
            name='senha_do_aluno',
            field=models.CharField(blank=True, default=mentorias.models.get_random_string, max_length=8, null=True, verbose_name='Senha para acesso'),
        ),
        migrations.AlterField(
            model_name='matriculaalunomentoria',
            name='senha_do_aluno',
            field=models.CharField(blank=True, default=mentorias.models.get_random_string, max_length=8, null=True, verbose_name='Senha para acesso'),
        ),
    ]
