# Generated by Django 4.2.1 on 2023-07-28 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0078_alter_matriculaalunomentoria_senha_do_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivosaluno',
            name='aluno',
        ),
        migrations.AddField(
            model_name='arquivosaluno',
            name='aluno_do_arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivosaluno_aluno', to='mentorias.alunos', verbose_name='Aluno'),
        ),
    ]
