# Generated by Django 4.2.1 on 2023-07-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0079_remove_arquivosaluno_aluno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivosaluno',
            old_name='aluno_do_arquivo',
            new_name='aluno',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='arquivos_aluno',
        ),
        migrations.AddField(
            model_name='alunos',
            name='arquivos_do_aluno',
            field=models.ManyToManyField(blank=True, help_text='Arquivos de um Aluno são arquivos disponíveis ao estudante selecionado.', related_name='alunosarquivos_do_aluno', to='mentorias.arquivosaluno'),
        ),
    ]
