# Generated by Django 4.2.1 on 2023-07-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0081_rename_aluno_arquivosaluno_arquivos_do_aluno_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivosaluno',
            name='arquivos_do_aluno_aluno',
        ),
        migrations.AlterField(
            model_name='alunos',
            name='arquivos_do_aluno',
            field=models.ManyToManyField(blank=True, help_text='Arquivos de um Aluno são arquivos disponíveis ao estudante selecionado.', to='mentorias.arquivosaluno'),
        ),
    ]
