# Generated by Django 4.2.1 on 2023-07-28 23:46

import django.core.validators
from django.db import migrations, models
import mentorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0082_remove_arquivosaluno_arquivos_do_aluno_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosDoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Criado por:')),
                ('arquivo_aluno', models.FileField(help_text='Insira arquivo em .pdf de até 5MB de tamanho.', null=True, upload_to=mentorias.models.aluno_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), mentorias.models.file_size], verbose_name='Arquvio mentoria')),
                ('email_aluno', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Aluno')),
            ],
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='arquivos_do_aluno',
        ),
        migrations.DeleteModel(
            name='ArquivosAluno',
        ),
    ]
