# Generated by Django 4.2.1 on 2023-05-18 02:18

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, help_text='Insira o telefone para contaco com Whatsapp. Ex:(99)999999999.', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Ó telefone para contato precisa             ser incerido com o DDD e os nove dígitos.', regex='\\d{11}$')], verbose_name='Telefone para contato')),
                ('business', models.BooleanField(default=False, verbose_name='Sou empresa')),
                ('policy_lang', models.CharField(blank=True, choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='en', max_length=5, null=True, verbose_name='Língua de aceitação da política')),
                ('dev_policy_lang', models.CharField(blank=True, choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='en', max_length=5, null=True, verbose_name='Língua de aceitação da política para desenvolvedores')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user_since', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Usuário desde')),
                ('email_checked', models.BooleanField(default=False, verbose_name='Email verificado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Id de usuário removido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de usuário removido')),
                ('user_since', models.DateTimeField(blank=True, null=True, verbose_name='Usuário desde')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da remoçao do usuário')),
                ('reason', models.CharField(default='Self removed', max_length=50, verbose_name='Razão da remoção do usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'estudante'), (2, 'mentor'), (5, 'adm')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que recebeu')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto da mensagem')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da mensagem')),
                ('openned', models.BooleanField(default=False, verbose_name='Visualizada')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que recebeu')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('uri_key', models.UUIDField(default=uuid.uuid4, verbose_name='Chave de acesso da url')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data do email')),
                ('confirmed', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da confimação')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(to='usuarios.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
