# Generated by Django 4.2.1 on 2023-05-20 01:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_roles_alter_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cnpj_faturamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CNPJ para faturamento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco_faturamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço para faturamento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Insira o telefone para contaco com Whatsapp. Ex:(99)999999999.', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Ó telefone para contato precisa         ser incerido com o DDD e os nove dígitos.', regex='\\d{11}$')], verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'estudante'), (2, 'mentor'), (3, 'ajudante'), (5, 'admin')], primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_redirect', models.SmallIntegerField(choices=[(1, 'Estudante'), (2, 'Mentor'), (3, 'Sempre perguntar')], default=3, verbose_name='Ir direto para o painel preferido ao iniciar sessão')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Preferências do usuário')),
            ],
        ),
    ]
