# Generated by Django 4.2.1 on 2023-05-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_customuser_business_remove_customuser_roles_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
