# Generated by Django 4.2.1 on 2023-05-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_deleteduser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='reason',
            field=models.CharField(default='Solicitado pelo usuário.', max_length=50, verbose_name='Razão da remoção do usuário'),
        ),
    ]
