# Generated by Django 4.2.1 on 2023-06-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='login_redirect',
            field=models.SmallIntegerField(choices=[(1, 'Estudante'), (2, 'Mentor'), (3, 'Sempre perguntar'), (4, 'Inicial')], default=4, verbose_name='Ir direto para o painel preferido ao iniciar sessão'),
        ),
    ]
