# Generated by Django 4.0 on 2023-09-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_enderecocobranca_endereco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecocobranca',
            name='endereco_estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
    ]
