# Generated by Django 4.0 on 2023-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_enderecocobranca_endereco_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cnpj_faturamento',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cpf_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPF do usuário'),
        ),
    ]
