# Generated by Django 4.2.3 on 2023-09-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0022_rename_termos_title_alteracoestermos_termo_title'),
        ('usuarios', '0025_alter_enderecocobranca_endereco_bairro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnderecoCobranca',
            new_name='PerfilCobranca',
        ),
    ]
