# Generated by Django 4.2.3 on 2023-09-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_rename_enderecocobranca_perfilcobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcobranca',
            name='perfil_pagamento',
            field=models.CharField(choices=[('cart', 'Cartão de crédito'), ('ppix', 'Pix'), ('bole', 'Boleto'), ('depo', 'Depósito bancário')], default='cart', max_length=4, null=True, verbose_name='Forma de pagamento'),
        ),
    ]
