# Generated by Django 4.2.3 on 2023-09-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_perfilcobranca_perfil_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcobranca',
            name='telefone1',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone de contato com o DDD*'),
        ),
        migrations.AlterField(
            model_name='perfilcobranca',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Outro telefone de contato com o DDD'),
        ),
    ]
