# Generated by Django 4.2.3 on 2023-09-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_alter_perfilcobranca_telefone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcobranca',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
