# Generated by Django 4.2.3 on 2023-09-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_perfilcobranca_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dev_policy_lang',
            field=models.CharField(blank=True, choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='pt', max_length=5, null=True, verbose_name='Língua de aceitação da política para desenvolvedores'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='policy_lang',
            field=models.CharField(blank=True, choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='pt', max_length=5, null=True, verbose_name='Língua de aceitação da política'),
        ),
    ]
