# Generated by Django 4.2.3 on 2023-09-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcobranca',
            name='perfil_pagamento',
            field=models.CharField(choices=[('cart', 'Cartão de crédito'), ('ppix', 'Pix'), ('bole', 'Boleto'), ('depo', 'Depósito bancário')], default='ppix', max_length=4, null=True, verbose_name='Forma de pagamento'),
        ),
    ]
