# Generated by Django 4.2.1 on 2023-05-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Título do texto')),
                ('text', models.TextField(verbose_name='Conteúdo do texto')),
                ('active', models.BooleanField(default=False, verbose_name='Texto está vigente(em uso)')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da criação')),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='pt-br', max_length=5, verbose_name='Lingua')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criou o texto')),
                ('staff_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criou o texto')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('pkey', models.IntegerField(blank=True, null=True, verbose_name='Id do texto')),
            ],
            options={
                'verbose_name_plural': 'Sobre nós',
            },
        ),
        migrations.CreateModel(
            name='AboutUsChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criaou ou modificou o texto')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criaou ou modificou o texto')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título do texto')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado do texto(ativo ou não)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo do texto')),
                ('pkey', models.IntegerField(blank=True, null=True, verbose_name='Id do texto')),
                ('mod_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da modificação')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ação realizada')),
            ],
            options={
                'verbose_name_plural': 'Modificações no texto "Sobre nós"',
            },
        ),
        migrations.CreateModel(
            name='DevPolicyAcepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('profile_id', models.IntegerField(verbose_name='Id do usuário')),
                ('acept_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da aceitação')),
            ],
        ),
        migrations.CreateModel(
            name='DevPolicyChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criaou ou modificou a política')),
                ('policy_user_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criaou ou modificou a política')),
                ('policy_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título da política')),
                ('policy_status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado da política(ativa ou não)')),
                ('policy_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo da política')),
                ('policy_pkey', models.IntegerField(blank=True, null=True, verbose_name='Id da política')),
                ('mod_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da modificação')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ação realizada')),
            ],
            options={
                'verbose_name_plural': 'Modificações na política para desenvolvedores',
            },
        ),
        migrations.CreateModel(
            name='DevPolicyRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Título da regra')),
                ('text', models.TextField(verbose_name='Conteúdo da regra')),
                ('begin_date', models.DateTimeField(verbose_name='Data do início da vigência')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do fim da vigência')),
                ('active', models.BooleanField(default=False, verbose_name='Regra está vigente(regra em uso)')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da criação')),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='pt-br', max_length=5, verbose_name='Lingua')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criou a regra')),
                ('policy_user_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criou a regra de desenvolvedores')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Política para desenvolvedores',
            },
        ),
        migrations.CreateModel(
            name='PolicyAcepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('profile_id', models.IntegerField(verbose_name='Id do usuário')),
                ('acept_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da aceitação')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criaou ou modificou a política')),
                ('policy_user_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criaou ou modificou a política')),
                ('policy_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título da política')),
                ('policy_status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado da política(ativa ou não)')),
                ('policy_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo da política')),
                ('policy_pkey', models.IntegerField(blank=True, null=True, verbose_name='Id da política')),
                ('mod_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da modificação')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ação realizada')),
            ],
            options={
                'verbose_name_plural': 'Modificações na política',
            },
        ),
        migrations.CreateModel(
            name='PolicyRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Título da regra')),
                ('text', models.TextField(verbose_name='Conteúdo da regra')),
                ('begin_date', models.DateTimeField(verbose_name='Data do início da vigência')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do fim da vigência')),
                ('active', models.BooleanField(default=False, verbose_name='Regra está vigente(regra em uso)')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da criação')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do usuário que criou a regra')),
                ('policy_user_id', models.IntegerField(blank=True, null=True, verbose_name='Id do usuário que criou a regra')),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese'), ('en', 'English')], default='pt-br', max_length=5, verbose_name='Lingua')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Política',
            },
        ),
    ]
