# Generated by Django 4.2.1 on 2023-05-18 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('politicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrules',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que criou a regra'),
        ),
        migrations.AddField(
            model_name='policyacepted',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicas.policyrules', verbose_name='Política da comunidade'),
        ),
        migrations.AddField(
            model_name='policyacepted',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='devpolicyrules',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que criou a regra'),
        ),
        migrations.AddField(
            model_name='devpolicyacepted',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='politicas.devpolicyrules', verbose_name='Política para desenvolvedores'),
        ),
        migrations.AddField(
            model_name='devpolicyacepted',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_policy', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que criou o texto'),
        ),
    ]
