# Generated by Django 4.2.1 on 2023-05-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='created_date',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='devpolicyrules',
            old_name='created_date',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='policyrules',
            old_name='created_date',
            new_name='criada_em',
        ),
    ]
