# Generated by Django 4.2.3 on 2023-09-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0003_rename_created_date_aboutus_criada_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'Sobre Nós textos'},
        ),
        migrations.AlterModelOptions(
            name='devpolicyrules',
            options={'verbose_name_plural': 'Políticas para desenvolvedores'},
        ),
    ]
