# Generated by Django 4.2.3 on 2024-02-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorias', '0055_alter_loginalunos_criada_em_aluno_login'),
        ('politicas', '0005_alter_policyacepted_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyacepted',
            name='login_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorias.loginalunos', verbose_name='Login do aluno'),
        ),
    ]
