# Generated by Django 4.2.3 on 2024-02-18 15:33

import django.core.validators
from django.db import migrations, models
import politicas.models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0007_remove_policyacepted_login_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrules',
            name='arquivo_politica',
            field=models.FileField(help_text='Insira arquivo em .pdf de até 10MB de tamanho.', null=True, upload_to=politicas.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), politicas.models.file_size], verbose_name='Arquvio da política'),
        ),
    ]
