# Generated by Django 4.2.3 on 2024-02-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0009_alter_policyrules_title'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE politicas_PolicyRules_id_seq RESTART WITH 1111;'),
        migrations.RunSQL(            
            'ALTER SEQUENCE politicas_PolicyAcepted_id_seq RESTART WITH 1122;'),
        migrations.RunSQL(
            'ALTER SEQUENCE politicas_DevPolicyRules_id_seq RESTART WITH 1133;'),
        migrations.RunSQL(
            'ALTER SEQUENCE politicas_DevPolicyAcepted_id_seq RESTART WITH 1133;')
    ]
